'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DealerCentral

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''dsAL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsAL As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsFL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsFL As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsGA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsGA As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsIL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsIL As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsMD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsMD As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsMN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsMN As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsOH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsOH As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsTN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsTN As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsVA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsVA As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsAZ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsAZ As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsCA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsCA As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsCO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsCO As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsNV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsNV As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsTX control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsTX As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsWA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsWA As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''grdAL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdAL As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''grdFL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdFL As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''grdGA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdGA As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''grdIL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdIL As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''grdMD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdMD As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''grdMN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdMN As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''grdOH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdOH As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''grdTN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdTN As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''grdVA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdVA As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''grdAZ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdAZ As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''grdCA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdCA As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''grdCO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdCO As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''grdNV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdNV As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''grdTX control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdTX As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''grdWA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdWA As Global.System.Web.UI.WebControls.GridView
End Class
